language: objective-c
xcode_project: RuntimeKit.xcodeproj # path to your xcodeproj folder
xcode_scheme: RuntimeKit

osx_image: xcode8.3


script: set -o pipefail && xcodebuild -scheme RuntimeKit | xcpretty
script: set -o pipefail && xcodebuild -scheme RuntimeKitTests test | xcpretty
